### ISSUE TITLE
unsupported arch

### ISSUE THREAD

**Issue by sabri-zaki** [CypherpunkArmory/UserLAnd-Assets-Kali#1]
When i run the command 
`sudo ./scripts/buildArch.sh $desiredArch`
It gives me this error 
`unsupported arch`
What is the solution for this error or its not support arm

**Comment by corbinlc** [comment]
We don't support Kali just yet.  We have one more issue to work through.  Once it works, you won't have to run that script, we will do it for you.

**Comment by sabri-zaki** [comment]
ok thanks and m waiting for new updates and features
